name: build and test

on:    
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  

jobs:
  build:

    name: build ${ {matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # can be added "windows-latest and macOS-latest" also 
        DOTNET_VERSION: [6.0.202] # The .NET SDK version to use

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
 
  deploy:
  
    name: deploy
    if: github.event.pull_request.merged == true
    needs: build
    uses: ./.github/workflows/CI.yml
    secrets:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        token: ${{ secrets.DOCKERHUB_TOKEN }}
      
      
      
     
